use_frameworks!

platform :ios, '9.0'

target 'AIFlagPhoneNumber_Example' do
  pod 'AIFlagPhoneNumber', :path => '../'

  target 'AIFlagPhoneNumber_Tests' do
    inherit! :search_paths

    
  end
end
